version: '3'

services:
    phpbenchmarks_code_validation_framework_hello_world:
        container_name: phpbenchmarks_code_validation_framework_hello_world
        tty: true
        build:
            context: ../../
            dockerfile: docker/codeValidation/Dockerfile
            args:
                DOCKER_UID: ${DOCKER_UID}
        environment:
            - VALIDATE_DEV=${VALIDATE_DEV}
            - REPOSITORIES_CREATED=${REPOSITORIES_CREATED}
            - RESULT_TYPE_SLUG=${RESULT_TYPE_SLUG}
        volumes:
            - ${INSTALLATION_PATH}:/var/www/phpbenchmarks
        extra_hosts:
            - php56.benchmark.loc:127.0.0.1
            - php70.benchmark.loc:127.0.0.1
            - php71.benchmark.loc:127.0.0.1
            - php72.benchmark.loc:127.0.0.1
            - php73.benchmark.loc:127.0.0.1
